name: Package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Configure npm for GitHub Packages
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set @mitigation-dot-team:registry=https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{secrets.MITIGATIONDOTTEAM}}
          npm install
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.MITIGATIONDOTTEAM}}